### ISSUE TITLE
Create-react-app fails to minify

### ISSUE THREAD

**Issue by adanielyan** [wopian/kitsu#154]
I use this package in my Create React App (CRA). I import it When I run ```npm run-script build``` I get the following error:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/kitsu/lib/index.mjs:1:1379

Read more here: http://bit.ly/2tRViJ9
```
Not sure what causes it, but according to link provided in the error message it CRA fails to compile es6 files.

**Comment by wopian** [comment]
ES6+ syntax is only compiled down to supported syntax where [not supported by our targets](https://github.com/wopian/kitsu/tree/master/packages/kitsu#node--browser-support). You may find it'll work fine by importing the legacy bundle:
```js
import Kitsu from 'kitsu/legacy'
```

Otherwise you'll have to wait until CRA 2.0 lands https://github.com/facebook/create-react-app/pull/3776

**Comment by gaearon** [comment]
https://reactjs.org/blog/2018/10/01/create-react-app-v2.html
