### ISSUE TITLE
Why use async/await in kitsu-core

### ISSUE THREAD

**Issue by sp90** [wopian/kitsu#350]
Hi, love your work on the project

I was reading through the source code is there any reason for async/await on all the methods provided?

It seems irrelevant since all methods can just be run right away?

Best regards
Simon

**Comment by wopian** [comment]
It's been a while since I've looked at the actual code for `kitsu-core`. 

Looks like I got a bit trigger-happy with promises several years ago when I split `kitsu-core` out of `kitsu`...by forcing `kitsu-core` to use async/await, and as you say they are entirely useless (effectively running synchronously in almost all of the methods).

I've stripped async/await from `kitsu-core` in https://github.com/wopian/kitsu/tree/async
