### ISSUE TITLE
Possible to have IE 11 support?

### ISSUE THREAD

**Issue by itsfadnis** [wopian/kitsu#419]
First of all thanks for this awesome library!

I know your docs mention IE won't be supported, but is there any changes I could make (polyfills or changing build target) to get it to work?

I'm looking to use this package in production but IE 11 is a deal breaker right now. Would appreciate any feedback.

**Comment by wopian** [comment]
>I know your docs mention IE won't be supported

Reason for the lack of IE11 support (dropped in 2018 with `6.0.0`) is because it more than doubled `kitsu-core` and `kitsu`'s size for just a single browser version (along with installing an at the time huge* runtime library to your `node_modules` that was only ever imported in the `kitsu/legacy` & `kitsu-core/legacy` builds).

\* in 2018, when the runtime was included with `kitsu` and `kitsu-core`, babel@6 runtime was [an additional 2 mB](https://packagephobia.now.sh/result?p=babel-runtime) in `node_modules`, In babel@7 [its just 165 kB](https://packagephobia.now.sh/result?p=%40babel%2Fruntime)

>is there any changes I could make (polyfills or changing build target) to get it to work?

Yes. You can re-add IE11 support by forking the repository and adding 2 dependencies that polyfills async/await and a bunch of EcmaScript features supported by modern browsers.

1. Fork repo and change a few things in this file: https://github.com/wopian/kitsu/blob/master/config/presets.js
	1. Add `'ie >= 11'` to `mainBrowsers` array (Lines 2-6)
	2. Change `babelHelpers` to `'runtime'` in `sharedConfig` (L22)
	3. Change `babelMain` to:
		```js
		const babelMain = {
		  ...sharedConfig,
		  plugins: [
		    '@babel/plugin-transform-runtime'
		  ],
		  presets: [
		    [ '@babel/env', {
		      targets: {
		        browsers: mainBrowsers,
		        node: minNode
		      },
		      modules: false
		    } ]
		  ]
		}
		```
2. Add `"@babel/plugin-transform-runtime": "~7.9.6"` as a `devDependency `in:
	- https://github.com/wopian/kitsu/blob/master/package.json
3. Add `"@babel/runtime": "~7.9.6"` as a `dependency `in:
	- https://github.com/wopian/kitsu/blob/master/packages/kitsu/package.json
	- https://github.com/wopian/kitsu/blob/master/packages/kitsu-core/package.json
4. In the `package.json` of `kitsu-core` and `kitsu`, change the following:
	- Scope the package names, e.g `"name": "@itsfadnis/kitsu-core"`
	- Add yourself to `"contributors": []"`
	- Update `"description"` to mention its a fork to support IE11`
5. Update all 3 README's to mention its an IE11 fork.
6. Run `yarn` at the top level to install the new dependencies in the Yarn Workspace.
7. Run `yarn release` at the top level to test, build & publish the packages
	- Make sure you're signed in to `npm` before running this.
