### ISSUE TITLE
Using a custom axios plugin / setting defaults

### ISSUE THREAD

**Issue by Excalibaard** [wopian/kitsu#465]
Thanks for this library! By far the most intuitive implementation of working with JSON:API in JS.

I was wondering if it would be possible to set defaults for the options and/or the underlying axios config.

We've got multiple different services that use similar configs where we have Headers or BaseUrls that are different, but some settings like camelCaseTypes, interceptors and axiosOptions are identical across almost all the services. Additionally, some of the resources we talk to are not JSON:API, so we have separate 'normal' axios instances for those.

In axios, I'm able to simply assign options to the 'defaults' key to have them always inserted, and override the defaults whenever I call axios.create(). But I'm not sure how to do something similar with the Kitsu class for the JSON:API resources. Now I have to import and assign the 'default settings' every time I construct a new instance in a different service. This is easily forgotten and overlooked, and is not very nice to work with when we do need an override.

What would be the best way to modify the Kitsu class before calling `new Kitsu(options)`? Would it be possible to use the custom axios plugin with our defaults instead of the 'raw' axios library for the internal `axios.create()`?

**Comment by wopian** [comment]
Hi @Excalibaard,

The axios instance the Kitsu class uses is exposed by the class, where you can add custom defaults (https://github.com/axios/axios#custom-instance-defaults)

E.g:
```js
const api = new Kitsu()
api.axios.defaults.baseURL = 3000
```

I'm currently away from home until Monday 31st so can't provide a more detailed answer until then unfortunately.

**Comment by Excalibaard** [comment]
Thanks for the swift response!

I hadn't realised I could access the entire axios instance besides the headers/interceptors that had been aliased, so that's a great tip. Though, I initialise a different client instance (sometimes multiple) for every 'service', as they use different baseUrls and authentication logic, but have other settings that are identical. Ideally I'd be able to set defaults _before_ initialisation.

My current code is doing something like this:

```js
// services/somethingService.js
import axiosOptions from './axiosOptions'; // What I'd normally put in the defaults, is imported and applied in every client instance, in every service file

const admin = new Kitsu({ ...options, axiosOptions })
const public = new Kitsu({ ...options, axiosOptions })
```

I'm looking for a solution like a plugin where I modify the base Kitsu class and import that instead:

```js
// plugins/kitsu.js
import Kitsu from 'kitsu';

// do things to modify the imported class, e.g. base axios config, default settings

export default Kitsu

// services/somethingService.js
import Kitsu from '~/plugins/kitsu'; // customized Kitsu class with defaults

const api = new Kitsu(options);
```

It may also just be my inexperience working with ES6 Classes that makes me unable to find a solution here.

**Comment by wopian** [comment]
The custom Axios instance created on initialisation _will_ inherit defaults set before initialisation if the [global Axios defaults ](https://github.com/axios/axios#global-axios-defaults) are modified. However:

- The `baseURL` of the custom Axios instance is set to a default value by the `Kitsu` class if not specified during initialisation in `options.baseURL` or `options.axiosOptions.baseURL`
  - Overriding whatever value is present in the Axios global defaults
- There are no modifiable global defaults for the Kitsu class-specific options (`options.camelCaseTypes` etc)
  - These can only be set during initialisation and after initialisation

Personally, I'm not a big fan of Axios' `axios.defaults` and prefer leaving the library defaults alone and creating separate instances for custom defaults (i.e deterministic behaviour on initialisation), so I likely won't add global defaults for the `Kitsu` class constructor options myself.

---
### Setting defaults during initialisation

```js
// ./plugins/kitsu.js
import Kitsu from 'kitsu'
import axiosOptions from './axiosOptions'

export { Kitsu }

export const kitsuDefaults = { 
  camelCaseTypes: true, 
  axiosOptions
}
```

```js
// ./services/one.js
import { Kitsu, kitsuDefaults } from './plugins/kitsu'

const options = {
  ...kitsuDefaults,
  baseURL: 'https://one.service/api`,
  headers: {
    ...
  }
}

const user = new Kitsu(options);
```

---
### Setting Axios defaults before initialisation

Not recommended, as it produces side-effects that will pollute all other Axios instances created after this

```js
import axios from 'axios'
import Kitsu from 'kitsu'

// Or anywhere in the code before `new Kitsu` is called
axios.defaults.headers.common = { 'X-Header': 'value' }

export { Kitsu }
```

---
### Caveats to be aware of

If you're setting different properties inside the same object (e.g `headers`) in `plugins` and `services`, I would suggest using [`merge-options`](https://www.npmjs.com/package/merge-options), otherwise you'll overwrite the other properties. E.g:

```js
// ./plugins/kitsu.js
export const kitsuDefaults = { headers: { 'X-Some-Header': 'value1' } }

// ./services/one.js
import { kitsuDefaults } from './plugins/kitsu'
const options= { ...kitsuDefaults, headers: { 'X-Another-Header': 'value2' } }
// Would produce the following output
{
  headers: {
    'X-Another-Header': 'value2'
  }
}
```

With `merge-options`:

```js
// ./plugins/kitsu.js
export const kitsuDefaults = { headers: { 'X-Some-Header': 'value1' } }

// ./services/one.js
import merge from 'merge-options'
import { kitsuDefaults } from './plugins/kitsu'

const serviceOptions = { headers: { 'X-Another-Header': 'value2' } }
const options = merge(kitsuDefaults, serviceOptions)
// Would produce the following output
{
  headers: {
    'X-Some-Header': 'value1',
    'X-Another-Header': 'value2'
  }
}
```

**Comment by Excalibaard** [comment]
That's a fair argument. I didn't know that axios.defaults are applied globally as I haven't had a case yet where I needed the base config *and* a custom defaults config, only a default with some small overrides. Global defaults are definitely a lot harder to trace. I'll stop using them before I run into problems.

In my opinion the difference between importing a plugin from the library directly or from a local export (with possible modifications) makes it clear when behavior is deterministic or not. You can trace the altered behavior back to the local file in that case, which is probably consciously made for a specific usecase.

Anyhow, thanks a lot for your time and your detailed response!
