### ISSUE TITLE
Change output directory name request

### ISSUE THREAD

**Issue by kacianoghelere** [wopian/kitsu#510]
Hi there! I'll try to be brief.

Can you consider changing the kitsu-core output directory from `lib/` to `dist/`? We are using it with react native and our build tool is recompiling the code, causing crashes and others errors. It took almost two days to find the problem cause and it happens because the builder ignores everything inside `dist/` directories, but it doesn't work the same way with the `lib/` dir.

I know that we could try to fix it on our side but I think that, by simply changing the output directory name, a lot of people could be spared from the headaches we had.

**Comment by wopian** [comment]
Hey @kacianoghelere, I can definitely do this to avoid the recompilation issues you're having with`kitsu-core` in React Native.

Fortunately due to the `exports` feature added in Node 12+ this can be a seamless behind the scenes change instead of a major breaking change, so I can safely fix this on 9.x and the alpha 10.x releases 👍

**Comment by kacianoghelere** [comment]
Hi @wopian, many thanks man! We're using the 10.x alpha version on our app, so we really appreciate it.

**Comment by wopian** [comment]
Released 10.0.0-alpha.9. 

- [CHANGELOG](https://github.com/wopian/kitsu/releases/tag/v10.0.0-alpha.9)
- [MIGRATING](https://github.com/wopian/kitsu/blob/master/packages/kitsu-core/MIGRATING.md#exports)
