### ISSUE TITLE
Fail to build for a browser using uglify

### ISSUE THREAD

**Issue by BANOnotIT** [wopian/kitsu#70]
I created and issue on [camelcase](https://github.com/sindresorhus/camelcase/issues/34) and they [said they aimed on node](https://github.com/sindresorhus/camelcase/issues/23#issuecomment-293357487), so could you change `camelcase` for `camel-case` in dependencies for example?

**Comment by wopian** [comment]
Use [`uglify-es` ] instead of `uglify`, as I won't be implementing this change. 

`camel-case` is a 27kb dependency while `camelcase` is only 1.3kb and all the browsers I target (>1% usage) support the ES2015+ features `camelcase` uses - besides IE 11 which I will drop support for soon as it doubles `kitsu`'s size. 

[`uglify-es`]:https://github.com/mishoo/UglifyJS2/tree/harmony

**Comment by wopian** [comment]
Little update - `4.x` has dropped `camelcase` as a dependency - I now do it myself for a few hundred bytes.

`4.x` also has a legacy version which targets IE8+:
```js
import Kitsu from 'kitsu/lib/legacy'
require('kitsu/lib/legacy')
```
